# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ece_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(200, 10, 431, 61))

        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)

        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")

        self.truth_table = QtWidgets.QTableWidget(self.centralwidget)
        self.truth_table.setGeometry(QtCore.QRect(110, 190, 591, 341))
        self.truth_table.setRowCount(5)
        self.truth_table.setColumnCount(5)
        self.truth_table.setObjectName("truth_table")

        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.truth_table.setItem(3, 3, item)

        self.calculate_button = QtWidgets.QPushButton(self.centralwidget)
        self.calculate_button.setGeometry(QtCore.QRect(350, 140, 113, 32))
        self.calculate_button.setObjectName("calculate_button")

        self.boolean_equation_text_box = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.boolean_equation_text_box.setGeometry(QtCore.QRect(220, 90, 371, 41))
        self.boolean_equation_text_box.setObjectName("boolean_equation_text_box")
        
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "Truth Table Generator"))
        __sortingEnabled = self.truth_table.isSortingEnabled()
        self.truth_table.setSortingEnabled(False)
        self.truth_table.setSortingEnabled(__sortingEnabled)
        self.calculate_button.setText(_translate("MainWindow", "Calculate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
